version: '2'

services:

  nginx:
    image: nginx:alpine
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf  
    command: [nginx-debug, '-g', 'daemon off;']
    links: 
      - suma
      - resta
      - potencia
    ports:
      - "8080:80"

  suma:
    build: ./suma

  resta:
    build: ./resta

  potencia:
    build:  ./potencia